[package]
name = "csimdv"
version = "0.1.0"
edition = "2024"


[build]
rustflags = ["-C", "target-feature=+aes"]

[dependencies]
lender = "0.4.0"

[[bench]]
path = "benches/benchmarks.rs"
name = "benchmarks"
harness = false

[dev-dependencies]
criterion = "0.7.0"
simd-csv = "0.10.3"
