[package]
name = "csimdv"
version = "0.1.0"
edition = "2024"

[[bench]]
path = "benches/benchmarks.rs"
name = "benchmarks"
harness = false

[dev-dependencies]
criterion = "0.7.0"
simd-csv = "0.10.3"


[profile.release]
opt-level = 3
lto = true
codegen-units = 1
